color_arr = ["Black",
             "White",
             "Silver",
             "Grey",
             "Red",
             "Blue",
             "Yellow",
             "Orange",
             "Green",
             "Gold",
             "Brown",
             ]
